# Generated by Django 3.2.18 on 2023-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_auto_20230218_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepation_time',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
