# Generated by Django 3.2.18 on 2023-02-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0003_auto_20230218_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingedients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_time',
            new_name='preparation_time',
        ),
    ]
