# Generated by Django 3.2.18 on 2023-03-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0006_auto_20230301_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
